apiVersion: apps/v1
kind: Deployment
metadata:
  name: addservice-deploy
  namespace: default
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    
  replicas: 2
  
  selector:
    matchLabels:
      app: addserviceapp
  
  template:
    metadata:
      labels:
        app: addserviceapp
    spec:
      volumes:
      - name: cache
        hostPath:
          path: /tmp
          type: Directory
      imagePullSecrets:
      - name: default-builder-registry-cred
      containers:
      - name: addserviceapp
        image: anahidcalcacr.azurecr.io/addservice:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - name: cache
          mountPath: /var/lib/docker
        # envFrom:
        #   - configMapRef:
        #       name: foobar-config
---
apiVersion: v1
kind: Service
metadata:
  name: addservice
  namespace: default
spec:
  selector:
    app: addserviceapp
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP # LoadBalancer # NodePort # 